version: '3.8'
services:
  app:
    build:
      context: ./build
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db

  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: senharoot
      MYSQL_DATABASE: crdc
      MYSQL_USER: seu_usuario
      MYSQL_PASSWORD: sua_senha_usuario
    ports:
      - "3306:3306"
    volumes:
      - ./dados_mysql:/var/lib/mysql